import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import RegistryStyledComponents from "@/lib/registryStyledComponent";
import RegistryAntd from "@/lib/registryAntd";
import { UIProvider } from "@/contexts";
import AuthContext from "@/contexts/AuthContext";
import { PlusOutlined } from "@ant-design/icons";
import FloatButtonForm from "@/components/FloatButtonForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <RegistryStyledComponents>
          <RegistryAntd>
            <UIProvider>
              <AuthContext>
                {children}
                <FloatButtonForm />
              </AuthContext>
            </UIProvider>
          </RegistryAntd>
        </RegistryStyledComponents>
      </body>
    </html>
  );
}
